import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import{ PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
// src/app/layout.tsx



// export default async function RootLayout({ children }: { children: React.ReactNode }) {
//   const res = await fetch('http://localhost:3000/api/clans/test', { cache: 'no-store' });
//   const clans = await res.json();

//   return (
//     <html lang="en">
//       <body>
//         <aside>
//           <h2>Clans</h2>
//           <ul>
//             {clans.map((clan: any) => (
//               <li key={clan.id}><h1>{clan.name}</h1><br/>{clan.description} </li>
//             ))}
//           </ul>
//         </aside>
//         {children}
//       </body>
//     </html>
//   );
// }


export default async function RootLayout({children} : { children: React.ReactNode }) {
  return(
    <html lang="en">
      <body>
        <h3>SENİ ÇOK SEVİYORUM BÜŞRA</h3>
        <h2>Hem de çooook çok seviyorum</h2>
        <h1>SELAM yağız </h1>
        <br />
        <p></p>
      </body>
    </html>
  );
}
